### ISSUE TITLE
Version 1.1.6 bug of checkbox and master version dictionaries initialize failure

### ISSUE THREAD

**Issue by 99MengXin** [liuyug/flask-mdict#7]
There is a bug in Release version 1.1.6 that causes the system to crash if you try to uncheck your first dictionary by clicking the checkbox. When this happens, you will receive a 500 error, and you will need to delete the `/flask-mdict-master/content/flask_mdict.db` file and restart it.

The Master version (as of March 16th, 2023) has fixed this bug. However, it has a problem with initializing dictionaries correctly, which can cause users to get stuck on the first page. To use the Master version, you can first initialize your dictionaries with version 1.1.6 and then switch to the Master version.

For example, if you use O8C dictionary and you put `O8C.jpg`, `O8C.mdd`, `O8C.mdx`, `O8C.css` in `/flask-mdict-master/content`, after initializing you should find `O8C.mdd.db`, `O8C.mdx.db`, `about_O8C.html`, `flask_mdict.db` have been created correctly in the same folder.

**Comment by liuyug** [comment]
Which version is your MDD dictionary? flask-mdict only support MDICT version 2.0.
May you put some log messages?

**Comment by 99MengXin** [comment]
I don't know my version of MDD dictionary. Could you advise how to check it?

However, when I did the same command on v.1.1.6, it worked.

Please see the log messages as below.

Master version
```
sudo flask run --host=0.0.0.0
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Initialize MDICT "O8C" {21D06180-EC2A-309F-B72E-22F973C49875} [Enable]...
Traceback (most recent call last):
  File "/usr/bin/flask", line 33, in <module>
    sys.exit(load_entry_point('Flask==1.1.2', 'console_scripts', 'flask')())
  File "/usr/lib/python3/dist-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/usr/lib/python3/dist-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask/cli.py", line 848, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "/usr/lib/python3/dist-packages/flask/cli.py", line 305, in __init__
    self._load_unlocked()
  File "/usr/lib/python3/dist-packages/flask/cli.py", line 330, in _load_unlocked
    self._app = rv = self.loader()
  File "/usr/lib/python3/dist-packages/flask/cli.py", line 392, in load_app
    app = locate_app(self, import_name, None, raise_if_not_found=False)
  File "/usr/lib/python3/dist-packages/flask/cli.py", line 257, in locate_app
    return find_best_app(script_info, module)
  File "/usr/lib/python3/dist-packages/flask/cli.py", line 83, in find_best_app
    app = call_factory(script_info, app_factory)
  File "/usr/lib/python3/dist-packages/flask/cli.py", line 119, in call_factory
    return app_factory()
  File "/home/pi/flask-mdict-test/flask-mdict-master/app.py", line 30, in create_app
    init_app(app, url_prefix='/')
  File "/home/pi/flask-mdict-test/flask-mdict-master/flask_mdict/__init__.py", line 45, in init_app
    mdicts, db_names = helper.init_mdict(Config.MDICT_DIR, Config.INDEX_DIR)
  File "/home/pi/flask-mdict-test/flask-mdict-master/flask_mdict/helper.py", line 292, in init_mdict
    idx = IndexBuilder2(mdx_file, index_dir=mdict_index_dir)
  File "/home/pi/flask-mdict-test/flask-mdict-master/flask_mdict/mdict_query2.py", line 49, in __init__
    self._make_mdx_index(self.get_index_db(self._mdx_file, self._index_dir))
  File "/home/pi/flask-mdict-test/flask-mdict-master/flask_mdict/mdict_query2.py", line 112, in _make_mdx_index
    super(IndexBuilder2, self)._make_mdx_index(db_name)
  File "/home/pi/flask-mdict-test/flask-mdict-master/flask_mdict/word_query/mdict_query.py", line 130, in _make_mdx_index
    returned_index = mdx.get_index(check_block = self._check)
AttributeError: 'MDX' object has no attribute 'get_index'
```

v 1.1.6
```
sudo flask run --host=0.0.0.0
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Initialize MDICT "O8C" {261481B1-8127-31ED-94C4-EF953C26D839} [Enable]...
	+ O8C.mdx
	+ O8C.mdd
Add "Google 翻译" [Enable]...
--- MDict is Ready ---
 * app db: /home/pi/flask-mdict-test/flask-mdict-1.1.6/content/flask_mdict.db
 * Word Frequency Database: /home/pi/flask-mdict-test/flask-mdict-1.1.6/content/ecdict_wfd.db"
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
10.0.4.10 - - [17/Mar/2023 15:29:54] "GET /?word=apple HTTP/1.1" 200 -
10.0.4.10 - - [17/Mar/2023 15:29:54] "GET /static//css/mdict.css HTTP/1.1" 308 -
10.0.4.10 - - [17/Mar/2023 15:29:54] "GET /static/css/mdict.css HTTP/1.1" 200 -
10.0.4.10 - - [17/Mar/2023 15:29:54] "GET /static/bootstrap-4.5.0/css/bootstrap.min.css HTTP/1.1" 200 -
10.0.4.10 - - [17/Mar/2023 15:29:54] "GET /static/fontawesome-5.14.0/css/all.min.css HTTP/1.1" 200 -
10.0.4.10 - - [17/Mar/2023 15:29:54] "GET /static/css/typeahead.css HTTP/1.1" 200 -
10.0.4.10 - - [17/Mar/2023 15:29:54] "GET /261481B1-8127-31ED-94C4-EF953C26D839/resource/O8C.css HTTP/1.1" 200 -
10.0.4.10 - - [17/Mar/2023 15:29:54] "GET /gtranslate/resource/css/reset.css HTTP/1.1" 200 -
10.0.4.10 - - [17/Mar/2023 15:29:54] "GET /static/jquery-3.5.1/jquery.min.js HTTP/1.1" 200 -
10.0.4.10 - - [17/Mar/2023 15:29:54] "GET /static/bootstrap-4.5.0/js/bootstrap.bundle.min.js HTTP/1.1" 200 -
10.0.4.10 - - [17/Mar/2023 15:29:54] "GET /static/js/mdict.js HTTP/1.1" 200 -
10.0.4.10 - - [17/Mar/2023 15:29:54] "GET /static/fontawesome-5.14.0/webfonts/fa-solid-900.woff2 HTTP/1.1" 200 -
10.0.4.10 - - [17/Mar/2023 15:29:54] "GET /261481B1-8127-31ED-94C4-EF953C26D839/resource/O8C.jpg HTTP/1.1" 200 -
10.0.4.10 - - [17/Mar/2023 15:29:54] "GET /static/Ox3000_Rect1_mod_web.png HTTP/1.1" 200 -
10.0.4.10 - - [17/Mar/2023 15:29:54] "GET /static/js/typeahead.bundle.min.js HTTP/1.1" 200 -
10.0.4.10 - - [17/Mar/2023 15:29:54] "GET /gtranslate/resource/google_translate.ico HTTP/1.1" 200 -
10.0.4.10 - - [17/Mar/2023 15:29:54] "GET /261481B1-8127-31ED-94C4-EF953C26D839/resource/css/reset.css HTTP/1.1" 200 -
10.0.4.10 - - [17/Mar/2023 15:29:54] "GET /261481B1-8127-31ED-94C4-EF953C26D839/resource/uk_pron.png HTTP/1.1" 200 -
10.0.4.10 - - [17/Mar/2023 15:29:54] "GET /261481B1-8127-31ED-94C4-EF953C26D839/resource/us_pron.png HTTP/1.1" 200 -
10.0.4.10 - - [17/Mar/2023 15:29:54] "GET /261481B1-8127-31ED-94C4-EF953C26D839/resource/pic/fruit_comp.jpg HTTP/1.1" 404 -
10.0.4.10 - - [17/Mar/2023 15:29:54] "GET /261481B1-8127-31ED-94C4-EF953C26D839/resource/thumb/apple.jpg HTTP/1.1" 404 -
10.0.4.10 - - [17/Mar/2023 15:29:55] "GET /favicon.ico HTTP/1.1" 302 -
10.0.4.10 - - [17/Mar/2023 15:29:55] "GET /static/logo.ico HTTP/1.1" 200 -
```

**Comment by liuyug** [comment]
error: `AttributeError: 'MDX' object has no attribute 'get_index'`

I have fixed this error. Pls update your local code.

`git pull`

**Comment by 99MengXin** [comment]
Thank you. It works now.
